# Generated by Django 2.2.1 on 2019-05-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchapp', '0002_auto_20190508_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('specialty', models.CharField(max_length=20)),
                ('experience', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Available',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organ', models.CharField(max_length=20)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'unique_together': {('user_id', 'organ')},
            },
        ),
    ]
