# Generated by Django 2.2.1 on 2019-05-09 21:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matchapp', '0003_available_doctors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Person',
        ),
    ]
